title: Eliseo Martelli
email: me@eliseomartelli.it
description: "I’m an Android and Web developer but I’m also into creative stuff."
url: "http://eliseomartelli.it" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: eliseomartelli
author: Eliseo Martelli
# Build settings

exclude: [vendor]

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-menus

disqus:
  shortname: eliseomartelli

collections:
  recipes:
    output: true
  thoughts:
    output: true
  photos:
    output: true

feed:
  collections:
    - thoughts

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: "post"
      permalink: /blog/:categories/:year/:month/:day/:title/

  - scope:
      type: recipes
    values:
      layout: "recipe"
      scrollable: true
      permalink: /recipes/:categories/:year/:month/:day/:title/

  - scope:
      type: photos
    values:
      layout: "post"
      permalink: /photos/:year/:month/:day/:title/

  - scope:
      type: thoughts
    values:
      layout: "post"
      permalink: /thoughts/:title/
