backend:
  name: github
  repo: eliseomartelli/eliseomartelli.it

media_folder: "assets/images"
publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Categories", name: "categories", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Published?", name: "published", widget: "boolean", default: true}
  - name: "thoughts"
    label: "Thoughts"
    folder: "_thoughts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Published?", name: "published", widget: "boolean", default: true}

display_url: https://eliseomartelli.it
