---
name: Lighthouse

# yamllint disable-line rule:truthy
on:
  push:
    branch: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Waiting for 200 from the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: waitFor200
        with:
          site_name: "eliseomartelli"
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        id: lighthouseCheck
        with:
          urls: '${{ steps.waitFor200.outputs.url }}'
